name:                symbolic-tophat
version:             0.1.0.0
# synopsis:
description:         Please see the README on GitHub at <https://github.com/timjs/symbolic-tophat#readme>
github:              "timjs/symbolic-tophat"
license:             BSD3
author:              "Tim Steenvoorden"
maintainer:          "tim.steenvoorden@me.com"
copyright:           "BSD3"
# category:            Web


extra-source-files:
  - README.md
  - CHANGELOG.md


dependencies:
  - base-noprelude
  - relude
  - mtl
  - ref-tf
  - text
  - prettyprinter
  # - containers
  - sbv


default-extensions:
  # Lifting limitations:
  - EmptyDataDecls
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  # - MultiParamTypeClasses

  # Syntactic conveniences:
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  - NumericUnderscores

  # Deriving:
  - DeriveGeneric
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving

  # Syntactic adjustments:
  - BangPatterns
  - KindSignatures
  - TypeOperators
  - MonadComprehensions
  - BinaryLiterals
  - NegativeLiterals
  - NoStarIsType
  - BlockArguments

  # Type annotations:
  - ScopedTypeVariables
  # - TypeApplications
  - PartialTypeSignatures
  - NamedWildCards

  # Prelude and overloading:
  # - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedLists

  # Type extensions:
  - ConstraintKinds
  - RankNTypes

  # Intermediate syntactic adjustments:
  - DefaultSignatures
  - PatternSynonyms
  - PatternGuards
  # - ApplicativeDo

  # Intermediate type extensions:
  # - FunctionalDependencies
  - GADTs
  - ExistentialQuantification

  # Advanced type extensions:
  - DataKinds
  - PolyKinds
  - TypeFamilies
  # - TypeFamilyDependencies


ghc-options:
  - -Weverything

  - -Wno-safe
  - -Wno-unsafe
  - -Wno-implicit-prelude
  - -Wno-missing-pattern-synonym-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-export-lists 


library:
  source-dirs: src


executables:
  symbolic-tophat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - symbolic-tophat
